name: Deploy bookhub-frontend

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image
              run: docker build -t ella0110/bookhub_frontend  .

            - name: Publish Image to docker hub
              run: docker push ella0110/bookhub_frontend:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull ella0110/bookhub_frontend:latest
            - name: Delete old container
              run: docker rm -f bookhub-frontend-container
            - name: Run Docker Container
              run: docker run -d -p 5173:80 --name bookhub-frontend-container -e VITE_API_BASE_URL='${{ secrets.VITE_API_BASE_URL }}' -e VITE_STRIPE_PUB_KEY='${{ secrets.VITE_STRIPE_PUB_KEY }}' ella0110/bookhub_frontend
